# Usa una imagen oficial de Python como base
FROM python:3.9-slim

# agrego el backend en el python path de forma explicita
ENV PYTHONPATH=/app

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de requerimientos
COPY requirements.txt /app/

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación
COPY . /app/

# Expón el puerto en el que corre Django (por defecto es el 8000)
EXPOSE 8000

# Comando para iniciar la aplicación de Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

