# Usa una imagen oficial de Node.js como base
FROM node:16

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de package.json y package-lock.json
COPY package*.json /app/

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . /app/

# Construye la aplicación React
RUN npm run build

# Expón el puerto en el que corre React (por defecto es el 3000)
EXPOSE 3000

# Comando para iniciar la aplicación de React
CMD ["npm", "start"]

