# Usamos la imagen base oficial de Nginx
FROM nginx:1.27.2

# Copiamos el archivo index.html a la carpeta predeterminada de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponemos el puerto 80 para acceder al servidor
EXPOSE 80

