name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Prueba3/index.html
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: Prueba3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t yourhouse/nginx-prueba3:latest .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push yourhouse/nginx-prueba3:latest

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 

    - name: Update ECS service to force new deployment
      run: |
        # Force a new deployment of the ECS service
        aws ecs update-service \
          --cluster PruebaCluster \
          --service web-service \
          --force-new-deployment
   
