# Pipeline para que cada cambio en index.html tenga un nuevo build y luego deploy con docker-compose
name: CI/CD Pipeline

on:
  push:
    paths:
      - index.html
      - Dockerfile
      - .github/workflows/index-build-deploy.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

 # 3. Construir la imagen Docker con número de versión incremental con los cambios del index
    - name: Build Docker Image
      run: |
        VERSION=v1.${{ github.run_number }}
        docker build -t yourhouse/nginx-prueba3:$VERSION .

    # 4. Subir la imagen a Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        VERSION=v1.${{ github.run_number }}
        docker push miusuario/nginx-prueba3:$VERSION

    # 5. Desplegar la nueva imagen en el entorno
    - name: Deploy to Docker Compose
      run: |
        VERSION=v1.${{ github.run_number }}
        docker-compose down
        docker-compose up -d
        
